# Generated by Django 3.1.2 on 2020-10-19 22:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('jumanji', '0002_remove_vacancy_skills'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vacancy',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
