# Generated by Django 3.1.2 on 2020-10-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumanji', '0003_auto_20201019_2232'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vacancy',
            managers=[
            ],
        ),
    ]
