# Generated by Django 3.1.2 on 2020-10-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumanji', '0006_auto_20201027_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default=1, max_length=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=1, upload_to='company_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(upload_to='speciality_images'),
        ),
    ]
