# Generated by Django 3.1.2 on 2020-11-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumanji', '0009_auto_20201129_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.CharField(max_length=64),
        ),
    ]
